name: second_shot
description: "Career App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  go_router: ^14.3.0
  flutter_bloc: ^8.1.6
  dropdown_search: ^6.0.1
  pinput: ^5.0.0
  permission_handler: ^11.3.1
  bloc: ^8.1.4
  flutter_advanced_drawer: ^1.3.7
  intl: ^0.20.2
  shared_preferences: ^2.3.5
  pdf: ^3.11.2
  path_provider: ^2.1.5
  # firebase_core: ^3.11.0
  # firebase_auth: ^5.4.2
  url_launcher: ^6.3.1
  # google_sign_in: ^6.2.2
  # sign_in_with_apple: ^6.1.4
  device_info_plus: ^11.3.0
  # firebase_messaging: ^15.2.3
  flutter_local_notifications: ^18.0.1
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  in_app_purchase: ^3.2.1
  open_file: ^3.5.10
  screenshot: ^3.0.0
  # firebase_remote_config: ^5.4.3
  webview_flutter: ^4.10.0
  equatable: ^2.0.7
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/data.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400 # Regular (default)
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500 # Medium
        - asset: assets/fonts/GeneralSans-SemiBold.otf
          weight: 600 # SemiBold
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700 # Bold
    - family: Lemon
      fonts:
        - asset: assets/fonts/Lemon-Regular.ttf
    - family: Times
      fonts:
        - asset: assets/fonts/times.ttf
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package

# - asset: assets/fonts/Lemon-Regular.ttf
# For details regarding fonts from package dependencies,
# see https://flutter.dev/to/font-from-package
